#!/bin/bash

if tmux list-sessions &>/dev/null; then
	tmux set -g status off
fi
clear
termdumpimg -x 0 -y 0 -w 0 -h 0 /usr/local/share/tmux-undercover/meme.png
pty-shell -x 24 -y 12 -w -48 -h -24
if tmux list-sessions &>/dev/null; then
	tmux set -g status on
fi
clear
