#!/bin/bash

if tmux list-sessions &>/dev/null; then
	tmux set -g status off
fi
clear
termdumpimg -x 0 -y 0 -w 0 -h 0 /usr/local/share/tmux-undercover/thematrix.png
pty-shell -x 20 -y 4 -w 58 -h 25
if tmux list-sessions &>/dev/null; then
	tmux set -g status on
fi
clear

