#!/bin/bash

dir_name="tmux-undercover"
pj_file="prefix-j"

data_path="${XDG_DATA_HOME:-$HOME/.local/share}"
dir_path="$data_path/$dir_name"

tmux unbind-key -n j
tmux unbind-key -T prefix j

pj_path="$dir_path/$pj_file"
if [ -f "$pj_path" ]; then
	pj=$(<"$pj_path")
	eval "tmux $pj"
fi

