#!/bin/bash

if tmux list-sessions &>/dev/null; then
	tmux set -g status off
fi
clear
termdumpimg -x 0 -y 0 -w 0 -h 0 /usr/local/share/tmux-undercover/bscode.png
pty-shell -x 25 -w 184 -y 12 -h 42
if tmux list-sessions &>/dev/null; then
	tmux set -g status on
fi
clear

